# Generated by Django 3.2.16 on 2023-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECycling', '0002_auto_20230108_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.IntegerField(null=True),
        ),
    ]
