# Generated by Django 3.2.16 on 2023-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECycling', '0003_auto_20230108_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='indumentaria',
            name='cod_indumentaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indumentaria',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indumentaria',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='cod_cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='cod_indumetaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cod_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
